travis:
  secure:
    BINSTAR_TOKEN: wgFsfRXHUqb+zZbYDh4Yv6q1HqcnybPOHznp2CYEvxk9bzjSH01PaQFXzX12glwZ+IW9OBMHdUSOJbAduoLSWIS69gDFNxtr+CraU6MDLL+akcIcJgo081lMQ+uSfdcI6PeY48HmDkqDEbDYokbziHvxnPaQxmrsrJ8eeIWcHJcupKv28/lZMtvyW8FvCywmb+Jki4Rc/kVgyxwgEuyHa544gQPNjeazmuBTDiPi6pdO1NV5ExdeRGYb55HPQvcou9tQdUI9LezHK1bVQg7RFADzbgkY6HQfPJHQXRkgngPsnbmK5Z+YKDWiJy/nGkoK4Z8E9KR5++Kpx3Uf/e5/v3yCYJQziCZP8O6WF1NpzXjLJRh1ngy3vrF5gKfMEWZeg1XVlkbwJ1bTcbUzkICKhjeEdh3Uvn/vEcVJGxpEvsBj+w7u82zKFXWVOU2u5uo4RMCGSSyVht4cCq9iSvEoUHHBujt+Bxjupq+Q0q5ky33s0kdtsKp8REg7SYf15Bq+TFsdIeW+Va+ZbOLcTVx/OWt0cCWZY+I6mwF7T9GszVA1buG7MiWXFhH3sh/bE0fN5UBChvXcUfls98iZo3t5VJLLqnbvYVZA1HwGJ5U8YENSE12wpktltnMXSgxhN0t4oppG2NmN6pRFBr8g9L3Ruae8S1JBa42BuUU+Cg9Ha5M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
